### ISSUE TITLE
"truffle compile" in code/truffle/METoken fails

### ISSUE THREAD

**Issue by amaramrahul** [ethereumbook/ethereumbook#789]
Here is the error:

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at Object.<anonymous> (/Users/rahul/ethereumbook/code/truffle/METoken/truffle-config.js:15:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

Platform: OS X. Tried with buffer version: 5.1.0, 5.0.8, 4.9.1, 4.8.0 and kept getting the same error.

**Comment by Meshugah** [comment]
Could you provide detail on what steps you followed?

**Comment by amaramrahul** [comment]
Below are the steps for reproducing the issue. I am using OS X El Capitan.
```
cd code/truffle/METoken
npm install
truffle compile
```

**Comment by TabiasP** [comment]
I'm getting the same error

**Comment by TabiasP** [comment]
The problem comes when installing: 
truffle-wallet-provider@0.0.5
ethereumjs-wallet@0.6.2
dotenv@6.1.0

**Comment by AnthonyMadia** [comment]
How was this resolved? Running into the same issue.
