### ISSUE TITLE
Building frontend for auction_dapp fails

### ISSUE THREAD

**Issue by unix0r** [ethereumbook/ethereumbook#971]
Hey guys, I'm trying to get the auction_dapp running as part of my master thesis, but somehow the example frontend is not building.

Just created a naked Ubuntu 20.04 in a VM for experimenting on this and following the instructions of the book I keep getting this error while installing sha3:

```
bc@ethereumhost:~/ethereumbook/code/auction_dapp/frontend$ npm install

> sha3@1.2.0 install /home/bc/ethereumbook/code/auction_dapp/frontend/node_modules/sha3
> node-gyp rebuild

make: Entering directory '/home/bc/ethereumbook/code/auction_dapp/frontend/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2167 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:36:64: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   36 |   hashlen = info[0]->IsUndefined() ? 512 : info[0]->Int32Value();
      |                                                                ^
In file included from /home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:26,
                 from /home/bc/.cache/node-gyp/10.18.1/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:2478:46: note: declared here
 2478 |   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      |                                              ^~~~~~~~~~
/home/bc/.cache/node-gyp/10.18.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/addon.cpp:49:23: warning: ‘new’ of type ‘SHA3Hash’ with extended alignment 32 [-Waligned-new=]
   49 |    obj = new SHA3Hash();
      |                       ^
../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
../src/addon.cpp:59:58: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
   59 |    info.GetReturnValue().Set(cons->NewInstance(argc, argv));
      |                                                          ^
In file included from /home/bc/.cache/node-gyp/10.18.1/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:3993:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const’
 3993 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
      |                                            ^~~~~~~~~~~
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:3996:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’
 3996 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
      |                                            ^~~~~~~~~~~
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::Update(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:97:49: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   97 |    Local<Object> buffer_obj = info[0]->ToObject();
      |                                                 ^
In file included from /home/bc/.cache/node-gyp/10.18.1/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:10046:15: note: declared here
10046 | Local<Object> Value::ToObject() const {
      |               ^~~~~
In file included from ../src/addon.cpp:1:
../src/addon.cpp: At global scope:
/home/bc/.cache/node-gyp/10.18.1/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/bc/.cache/node-gyp/10.18.1/include/node/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cpp:164:1: note: in expansion of macro ‘NODE_MODULE’
  164 | NODE_MODULE(sha3, SHA3Hash::Init)
      | ^~~~~~~~~~~
In file included from /home/bc/.cache/node-gyp/10.18.1/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/bc/.cache/node-gyp/10.18.1/include/node/node_object_wrap.h:84:78:   required from here
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/home/bc/.cache/node-gyp/10.18.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [sha3.target.mk:107: Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/bc/ethereumbook/code/auction_dapp/frontend/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/bc/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-33-generic
gyp ERR! command "/home/bc/.nvm/versions/node/v10.18.1/bin/node" "/home/bc/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bc/ethereumbook/code/auction_dapp/frontend/node_modules/sha3
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bc/.npm/_logs/2020-06-04T06_43_19_511Z-debug.log
```

This is the mentioned debug log file:
[2020-06-04T06_43_19_511Z-debug.log](https://github.com/ethereumbook/ethereumbook/files/4728067/2020-06-04T06_43_19_511Z-debug.log)

I have read somewhere, that the current node version does not work with node-gyp, so I just downgraded it to 10.18.1. The sha3 package is also installed with version 1.2.0 globally.

Any ideas how I can get this work?

**Comment by unix0r** [comment]
https://github.com/ethereumbook/ethereumbook/pull/957/files

Did the trick. :-)
